spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com/
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 1.0
      embedding:
        options:
          model: text-embedding-ada-002
    vectorstore:
      qdrant:
        host: localhost
        port: 6334                   # gRPC port used by the Spring AI Qdrant store
        collection-name: docs        # collection where embeddings will be stored
        use-tls: false
        initialize-schema: true